
FROM docker.io/denoland/deno:latest AS builder

ENV API_URL="http://localhost:5095"

# Set working directory
WORKDIR /build

# Copy application source code
ADD . .

RUN deno i
RUN deno task build

FROM docker.io/denoland/deno:latest
WORKDIR /app

ENV API_URL="http://localhost:5095"

COPY --from=builder /build/build ./build
COPY --from=builder /build/deno.json ./deno.json
COPY --from=builder /build/package.json ./package.json

RUN deno i

# Create non-root user
RUN useradd -l -u 10001 -s /sbin/nologin -M appuser

EXPOSE 3000

USER appuser
CMD ["deno", "run", "--allow-all", "--unstable-bare-node-builtins", "build/index.js"]